name: camera-app
version: 3.0.0.658
summary: Ubuntu Camera Application
description: Camera application to take pictures and shoot videos
confinement: strict

apps:
  camera-app:
    command: bin/camera.wrapper
    plugs: [unity7, opengl, camera, pulseaudio, home]

parts:
  wrapper:
    source: .
    plugin: dump
    organize:
      camera.wrapper: bin/camera.wrapper
    stage:
      - bin/camera.wrapper
    snap:
      - bin/camera.wrapper

  camera:
    source: .
    plugin: cmake
    configflags: [-DCMAKE_INSTALL_PREFIX=/usr, -DCLICK_MODE=off]
    build-packages:
      - gcc
      - g++
      - cmake
      - gettext
      - intltool
      - pkg-config
      - qtbase5-dev
      - qtdeclarative5-dev
      - libusermetricsinput1-dev
      - qtmultimedia5-dev
    stage-packages:
      - ubuntu-sdk-libs
      - qtubuntu-desktop
      - qml-module-qtpositioning
      - qtdeclarative5-unity-action-plugin
      - qtdeclarative5-usermetrics0.1
      - qtdeclarative5-ubuntu-content1
      - qtdeclarative5-ubuntu-ui-extras0.2
      - qtdeclarative5-ubuntu-thumbnailer0.1
      - xdg-user-dirs
    after: [desktop-qt5]
