name: camera-app
version: 3.0.0.658
summary: Ubuntu Camera Application
description: Camera application to take pictures and shoot videos
confinement: devmode
grade: devel

apps:
  camera-app:
    command: desktop-launch $SNAP/bin/camera.wrapper
    plugs: [unity7, unity8, opengl, camera, pulseaudio, home, platform]

plugs:
  platform:
    interface: content
    content: ubuntu-app-platform1
    target: ubuntu-app-platform

parts:
  wrapper:
    source: snap/
    plugin: dump
    organize:
      camera.wrapper: bin/camera.wrapper

  camera-app:
    source: .
    plugin: cmake
    configflags: [-DCMAKE_INSTALL_PREFIX=/usr, -DCLICK_MODE=off]
    build-packages:
      - gcc
      - g++
      - cmake
      - gettext
      - intltool
      - pkg-config
      - qtbase5-dev
      - qtdeclarative5-dev
      - libusermetricsinput1-dev
      - qtmultimedia5-dev
    stage-packages:
      - xdg-user-dirs
      - qtdeclarative5-ubuntu-ui-extras0.2
    after: 
      - desktop-ubuntu-app-platform
